#pragma config(Motor,  port1,           leftMotor,     tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port8,           armMotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           clawMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                           - Dual Joystick Control with Arm - 2 Remotes -                           *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Left and the Right joysticks on Remote Control 1 to run the robot using     *|
|*  "arcade control". The Group 5 and 6 buttons on the top-right of Remote Control 2 are used to raise  *|
|*  and lower the arm.                                                                                *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
|*    Motor - Port 6          armMotor             VEX Motor           Arm motor                      *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
	while(1 == 1)
	{
		//Driving Motor Control with Remote Control 1
	motor[leftMotor]  = (vexRT[Ch2] + vexRT[Ch1])/2;  // (y + x)/2
		motor[rightMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;  // (y - x)/2

		//Arm Control with Remote Control 2
		if(vexRT[Btn5UXmtr2] == 1)       	//If button 5U is pressed... when button 5 (topleft)is pressed  
		{
			motor[armMotor] = 127;    	//...raise the arm... 
		}
		else if(vexRT[Btn5DXmtr2] == 1)  	//Else, if button 5D (bottom left) is pressed...
		{
			motor[armMotor] = -127;   	//...lower the arm.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[armMotor] = 0;      	//...don't move the arm.
		}

		// Open, close or do not move claw
		if(vexRT[Btn6UXmtr2] == 1)       	//If Button 6U(top right) is pressed...
		{
			motor[clawMotor] = 127;  		//...close the gripper.
		}
		else if(vexRT[Btn6DXmtr2] == 1)  	//Else, if button 6D is pressed...
		{
			motor[clawMotor] = -127; 		//...open the gripper.
		}
		else                      		//Else (neither button is pressed)...
		{
			motor[clawMotor] = 0;  //...stop the gripper.
		if (vexRT[Btn8RXmtr2] ==1 )			// If button 8R is pressed
		{
			motor[wheelMotor]== 127*2;		// Rotate the wheel at full speed
		}
		else // if the 8R button is not pressed
		{
			motor[WheelMotor]== 0 //don't rotate the wheel atfull speed
		}
	}
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
